### ISSUE TITLE
update this app to flutter latest version 

### ISSUE THREAD

**Issue by adilwahla** [adilwahla/Clima-weather-app#1]
the current version of app is quite outdated this will be an easy task

**Comment by Shubham9455** [comment]
> the current version of app is quite outdated this will be an easy task

I run this app after some changes on flutter 3.0.5, and it runs fine is it the sufficient or I have to do something more

**Comment by adilwahla** [comment]
cool just add Screenshots in ReadMe and send PR with updated code  specially pubspec.yaml

**Comment by Shubham9455** [comment]
> cool just add app's Screenshots in ReadMe and send PR with updated code specially pubspec.yaml then I will merge

@adilwahla please add Hacktoberfest accepted tag in my PR or your REPO

**Comment by adilwahla** [comment]
merge fixes#1

**Comment by Shubham9455** [comment]
> merge fixes#1
I think you added hactoberfest label to issue after my PR was merged so it is not counting as my valid PR please label my PR as hactoberfest accepted

**Comment by Shubham9455** [comment]
![Screenshot from 2022-10-03 21-49-45](https://user-images.githubusercontent.com/95691442/193628611-5239e1fe-b4ee-4ebd-a27d-a57ca548650b.png)

**Comment by adilwahla** [comment]
ok you can contribute further and this time label will be added
hacktoberfest makes differ in applicant vs maintainers since i have also participated may be that is an issue
