### ISSUE TITLE
Add App icon for both Android and ios 

### ISSUE THREAD

**Issue by adilwahla** [adilwahla/Clima-weather-app#4]
**Step#01**
- go to the app icon generator site 
- generate icons 
- add icons in relevant folders
**Step#02**
- Run app
- take screenshot of app icon
- add screenshot in Readme
- open PR 
**_Note: Make sure add weather/climate relevant icon_**

**Comment by amnindersingh12** [comment]
Hey, can I pick this up?

**Comment by adilwahla** [comment]
Sure

**Comment by Shubham9455** [comment]
> **Step#01**
> 
> * go to the app icon generator site
> * generate icons
> * add icons in relevant folders
>   **Step#02**
> * Run app
> * take screenshot of app icon
> * add screenshot in Readme
> * open PR
>   **_Note: Make sure add weather/climate relevant icon_**

Hey I have A PR ready please add hactoberfest accepted label this time to this issue and as well as my PR before merging it

**Comment by adilwahla** [comment]
@amnindersingh12 you can contribute in other so many issues there is alot of room yet 
- 7 day weather forecast feature using Api
- documentation improvement is required 
- can introduce new features 
- can add github actions 
- can give release
